[build]
builder = "nixpacks"
nixpacksConfigPath = "nixpacks.toml"
buildCommand = "echo building!"

[deploy]
startCommand = "echo starting!"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"